name: Xamarin CI

on:
  push:

jobs:
  Build: 
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v4
    - name: Build artifacts
      run: ./build.sh
      
  Android:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Android
      run: |
        dotnet restore
        cd Samples/mParticle.Xamarin.Android.Sample
        dotnet build
        
  iOS:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: iOS
      run: |
        dotnet restore
        cd Samples/mParticle.Xamarin.iOS.Sample
        dotnet build
