name: Xamarin CI

on:
  push:

jobs:
  Build: 
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: Build artifacts
      run: ./build.sh
      
  Android:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd Samples/mParticle.Xamarin.Android.Sample
        msbuild
        
  iOS:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        nuget restore
        cd Samples/mParticle.Xamarin.iOS.Sample
        msbuild
