name: Xamarin CI

on:
  push:

jobs:
  Build: 
    runs-on: macOS-14
    steps:
    - uses: actions/checkout@v4
    - name: Install Mono Framework
      run: brew install mono
    - name: Install MAUI workload
      run: dotnet workload install maui
    - name: Build artifacts
      run: ./build.sh